apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
      version: blue
  template:
    metadata:
      labels:
        app: static-website
        version: blue
    spec:
      containers:
        - name: static-website-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static-content
          configMap:
            name: static-website-blue # Uses the created ConfigMap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
      version: green
  template:
    metadata:
      labels:
        app: static-website
        version: green
    spec:
      containers:
        - name: static-website-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static-content
          configMap:
            name: static-website-green # Uses the second ConfigMap
